version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  
  job_manager:
    image: apache/flink:1.20
    container_name: flink_jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job_manager
  
  task_manager:
    image: apache/flink:1.20
    container_name: flink_taskmanager
    depends_on:
      - job_manager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=job_manager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2