blob.server.port: 6124
taskmanager.memory.process.size: 1728m
taskmanager.bind-host: 0.0.0.0
high-availability.type: NONE
taskmanager.memory.network.min: 64mb
jobmanager.rpc.address: job_manager
jobmanager.memory.process.size: 1600m
state.savepoints.dir: file:///tmp/flink-savepoints
taskmanager.memory.network.fraction: 0.1
jobmanager.rpc.port: 6123
taskmanager.rpc.port: 6122
query.server.port: 6125
rest.bind-address: 0.0.0.0
rest.port: 8081
jobmanager.bind-host: 0.0.0.0
taskmanager.memory.network.max: 1gb
taskmanager.host: task_manager
parallelism.default: 1
taskmanager.numberOfTaskSlots: 2
rest.address: job_manager
state.backend: hashmap
state.checkpoints.dir: file:///tmp/flink-checkpoints
